#ifndef LED_COLORS_H
#define LED_COLORS_H

#define LED_BRIGHTNESS 10

#define LED_COLOR_OFF     0, 0, 0
#define LED_COLOR_WHITE   LED_BRIGHTNESS, LED_BRIGHTNESS, LED_BRIGHTNESS
#define LED_COLOR_RED     LED_BRIGHTNESS, 0, 0
#define LED_COLOR_GREEN   0, LED_BRIGHTNESS, 0
#define LED_COLOR_BLUE    0, 0, LED_BRIGHTNESS
#define LED_COLOR_YELLOW  LED_BRIGHTNESS, LED_BRIGHTNESS, 0
#define LED_COLOR_CYAN    0, LED_BRIGHTNESS, LED_BRIGHTNESS
#define LED_COLOR_MAGENTA LED_BRIGHTNESS, 0, LED_BRIGHTNESS

#endif // LED_COLORS_H